### ISSUE TITLE
Match and Sync between file formats

### ISSUE THREAD

**Issue by walterrowe** [walterrowe/capture-one-scripts#5]
I reached out to John Beardsley, the author of this amazing file sync tool called [Syncomatic](http://www.beardsworth.co.uk/lightroom/syncomatic/). I inquired whether he would be interested in porting his tool to Capture One. He wrote the tool in Adobe scripting language and has no interest in porting it to Capture One.

This would make a terrific tool to write in Python. Click the link to see all its features.

**Comment by emorydunn** [comment]
I hope this isn't too much self-promotion, but it might save some time writing a new script from a clean slate. I recently updated [Capturebot](https://capturebot.app/) to be able to map and sync metadata between files.

**Comment by walterrowe** [comment]
Does it automatically identify matching pairs of images to sync between? The Lightroom tool lets you select a batch of images and it does the file matching for you. Select 1000 DNG and NEF files, tell it which way to sync (DNG to NEF or NEF to DNG), and it finds the matching DNG/NEF pairs and does it all.

If you wrote that, I would pay for it.

**Comment by emorydunn** [comment]
It does indeed. The matching system is very [flexible](https://capturebot.app/help/matching-headers/), but the simplest mode is to simply match file names exactly. The primary use case was bringing AD ratings from JPGs back into the RAW files, but it can read from and write to anything Exiftool can.

**Comment by walterrowe** [comment]
Very cool! Does it support hierarchical keywords? C1 says it supports them and does show them in the keyword tool. It doesn't export keywords in hierarchical format.

Can it run as a script inside C1 and use a C1 selection as its source? The LR plugin runs inside of LR.

**Comment by emorydunn** [comment]
I haven't tested it specifically with hierarchical keywords, but they ought to be preserved as long as you use the source value. 

Capture One's plugin SDK is… lacking, to say the very least, so it's a standalone application. Right now Capturebot can't use the selected images as a datasource, but it's on the roadmap. You can drag images from C1 into Capturebot, though. Adding AppleScript support is also in the works.

**Comment by walterrowe** [comment]
Sweet!

**Comment by walterrowe** [comment]
@emorydunn - see the [dng2raw](/walterrowe/capture-one-scripts/tree/master/dng2raw) script I added. I would like to discuss more details about the matching code you have. I discovered that some derivative DNG files have a Create Date tag value that differs from the OriginalDateTime tag value. I had to employ exiftool to get the original create date from the dng files and camera native raw files. Not ideal but Capture One had the incorrect create date based on the DNG file so Capture One's dates could not be relied upon for comparing whether two images were matching pairs based on time stamp.

**Comment by emorydunn** [comment]
I'd be happy to answer talk about the file matching, feel free to shoot me an email with any questions.

**Comment by walterrowe** [comment]
@emorydunn - message sent via your website. also see the latest BACK-to-RAW. It now lets you choose source and target file types, and what you want to synchronize (one or more of adjustments, ratings, labels, keywords, metadata).

**Comment by walterrowe** [comment]
This issue is closed with the implementation of [back-to-raw](https://github.com/walterrowe/capture-one-scripts/tree/master/back-to-raw/).
