### ISSUE TITLE
any interest in building a time-lapse script/program?

### ISSUE THREAD

**Issue by richonguzman** [walterrowe/capture-one-scripts#8]
any interest in building a time-lapse script/program?

so far I have an almost working C1 time-lapse program (alla LRTimelapse-ish) in its bare-bones

**Comment by walterrowe** [comment]
@richonguzman - Did you ever complete this?

**Comment by richonguzman** [comment]
I had it running on my local pc

Will have to dig a little to make up to date and test if runs again

Although I thing it would be good to call it like a apple script 

But the sketch runs on python

**Comment by walterrowe** [comment]
@richonguzman are you using python to control capture one? I'm interested in learning more about this.

**Comment by walterrowe** [comment]
I am closing this issue.

**Comment by walterrowe** [comment]
I am closing this issue.

**Comment by walterrowe** [comment]
I am closing this issue.
